version: "3.9"

services:
  postgres:
    container_name: "plerk_postgres"
    image: "postgres:12.7-alpine"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: "always"

  redis:
    container_name: "plerk_redis"
    image: "redis:7.0-alpine3.15"
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: "always"

  rabbitmq:
    container_name: "plerk_rabbitmq"
    image: "rabbitmq:3.8-alpine"
    expose:
      - "5672"
    ports:
      - "5672:5672"
    restart: "always"

  api:
    &api
    container_name: "plerk_api"
    build: .
    depends_on:
      - "postgres"
      - "rabbitmq"
      - "redis"

  celery:
    <<: *api
    container_name: "plerk_celery"
    depends_on:
      - "rabbitmq"
      - "redis"
      - "api"

  # Used ONLY IN STAGING OR PRODUCTION ENVIRONMENT.
  celerybeat:
    <<: *api
    container_name: "plerk_celerybeat"
    depends_on:
      - "api"
      - "celery"


volumes:
  postgres_data: {}
  redis_data: {}
