version: "3.9"

services:
  postgres:
    container_name: "plerk_postgres"
    image: "postgres:12.7-alpine"
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: "always"

  api:
    container_name: "plerk_api"
    build: .
    depends_on:
      - "postgres"


volumes:
  postgres_data: {}
