# Generated by Django 3.2.13 on 2022-05-16 00:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('is_active', models.BooleanField(default=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('closed', 'closed'), ('reversed', 'reversed'), ('pending', 'pending')], max_length=10)),
                ('status_approved', models.BooleanField()),
                ('final_payment', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
